return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	event = { "BufReadPost", "BufNewFile" },
	opts = {
		ensure_installed = { 
      "lua", 
      "vim", 
      "vimdoc", 
      "markdown",
      "clojure",
      "scheme",
      "java",
      "c_sharp",
      "c",
      "cpp",
      "javascript",
      "typescript",
      "tsx",
      "html",
      "css",
      "json",
    },
		auto_install = true,
		highlight = { enable = true },
		indent = { enable = true },
	},
}
